### ISSUE TITLE
Make all translation in French

### ISSUE THREAD

**Issue by payagej** [rocky-linux/rockylinux.org-gatsby#123] opened 2021-05-25 19:04 UTC
## Describe the bug

With the new release of the translation system, most of the website isn't translate in French

## To Reproduce

Go to on most of page in French and see that it's not translated

## Expected behavior

Text translated

**Comment by brianclemens** [comment] 2021-05-25 21:38
Duplicate of #97

**Closed as completed by brianclemens** 2021-05-25 21:38 UTC
